---
AWSTemplateFormatVersion: 2010-09-09

Description: CI/CD Pipeline for updating a Proton Template

Parameters:

  TemplateCode:
    Type: String
    Description: The unique template code - used in bucket name

  EnvCode:
    Type: String
    Description: The environment code

  AppCode:
    Type: String
    Description: The environment code

  TemplateType:
    Type: String
    AllowedValues:
      - environment
      - application
  
  ProtonTemplatesBucketARN:
    Type: String
    Description: Proton Templates Bucket ARN

  BuildArtifactBucketARN:
    Type: String
    Description: Proton Build Artifacts Bucket ARN

  ProtonPipelineServiceRoleArn:
    Type: String
    Description: IAM Role for proton pipeline service

  GitSourceRepo:
    Type: String
    Description: GitHub source repository

  GitBranch:
    Type: String
    Description: Git repository branch - change triggers a new build
    Default: main

  GitHubToken:
    Type: String
    NoEcho: true
    Description: "GitHub API token - see: https://github.com/blog/1509-personal-api-tokens"

  GitHubUser:
    Type: String
    Description: GitHub username or organization

  CodeBuildDockerImage:
    Type: String
    Description: CodeBuild docker image
    Default: aws/codebuild/amazonlinux2-x86_64-standard:3.0

Conditions :
  IsEnvironment : !Equals [!Ref TemplateType, environment]

Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !If [ IsEnvironment,
          !Join [ "-", [ !Ref TemplateCode, !Ref EnvCode, env, proton, template ] ],
          !Join [ "-", [ !Ref TemplateCode, !Ref AppCode, app, proton, template ] ],
        ]
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Select [ 5, !Split [ ':', !Ref BuildArtifactBucketARN ] ]
      Stages:
        - Name: Source
          Actions:
            - Name: App
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: !Ref GitHubUser
                Repo: !Ref GitSourceRepo
                Branch: !Ref GitBranch
                OAuthToken: !Ref GitHubToken
              OutputArtifacts:
                - Name: App
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: App
              OutputArtifacts:
                - Name: BuildOutput
              RunOrder: 1
      Tags:
        - Key: TemplateCode
          Value: !Ref TemplateCode

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !If [IsEnvironment,
          !Join [ "-", [!Ref TemplateCode, !Ref EnvCode, env, proton, template] ],
          !Join [ "-", [!Ref TemplateCode, !Ref AppCode, app, proton, template] ],
        ]
      ServiceRole: !Ref CodeBuildRole
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          ---
          version: 0.2
          phases:
            install:
              commands:
                - printenv
                - aws s3 cp s3://aws-proton-preview-public-files/model/proton-2020-07-20.normal.json .
                - aws s3 cp s3://aws-proton-preview-public-files/model/waiters2.json .
                - aws configure add-model --service-model file://proton-2020-07-20.normal.json --service-name proton-preview
                - mv waiters2.json ~/.aws/models/proton-preview/2020-07-20/waiters-2.json
                - rm proton-2020-07-20.normal.json
            pre_build:
                commands:
                - if [[ $TEMPLATE_TYPE == "environment" ]]; then echo -e "DEPLOYING AN ENVIRONMENT TEMPLATE"; fi
                - if [[ $TEMPLATE_TYPE == "application" ]]; then echo -e "DEPLOYING AN APPLICATION TEMPLATE"; fi
            build:
              commands:
                - if [[ $TEMPLATE_TYPE == "environment" ]]; then
                    aws proton-preview create-environment-template --endpoint-url https://proton.${AWS_REGION}.amazonaws.com --region ${AWS_REGION} --name ${TEMPLATE_CODE}-${ENVIRONMENT_CODE} --display-name ${TEMPLATE_CODE}-${ENVIRONMENT_CODE}; 
                  fi
                - if [[ $TEMPLATE_TYPE == "application" ]]; then
                    aws proton-preview create-service-template --endpoint-url https://proton.${AWS_REGION}.amazonaws.com --region ${AWS_REGION} --name ${TEMPLATE_CODE}-${APPLICATION_CODE} --display-name ${TEMPLATE_CODE}-${APPLICATION_CODE};
                  fi
            post_build:
              commands:
                - printenv
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Type: LINUX_CONTAINER
        Image: !Ref CodeBuildDockerImage
        EnvironmentVariables:
          - Name: TEMPLATE_CODE
            Value: !Ref TemplateCode
          - Name: PROTON_TEMPLATES_BUCKET_NAME
            Value: !Ref ProtonTemplatesBucketARN
          - Name: PROTON_PIPELINE_SERVICE_ROLE_ARN
            Value: !Ref ProtonPipelineServiceRoleArn
          - Name: TEMPLATE_TYPE
            Value: !Ref TemplateType
          - Name: ENVIRONMENT_CODE
            Value: !Ref EnvCode
          - Name: APPLICATION_CODE
            Value: !Ref AppCode
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: !Ref CodeBuildLogGroup
      Tags:
        - Key: TemplateCode
          Value: !Ref TemplateCode

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !If [ IsEnvironment,
          !Join [ "-", [ !Ref TemplateCode, !Ref EnvCode, env, proton, template, codebuild, role ] ],
          !Join [ "-", [ !Ref TemplateCode, !Ref AppCode, app, proton, template, codebuild, role ] ],
        ]
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref CodeBuildPolicy
      Tags:
        - Key: TemplateCode
          Value: !Ref TemplateCode

  CodeBuildPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !If [ IsEnvironment,
          !Join [ "-", [ !Ref TemplateCode, !Ref EnvCode, env, proton, template, policy ] ],
          !Join [ "-", [ !Ref TemplateCode, !Ref AppCode, app, proton, template, policy ] ],
        ]
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:UpdateItem
              - dynamodb:PutItem
            Resource: !GetAtt TemplateVersionDynamoDbTable.Arn
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:GetObjectVersion
            Resource: !Sub ${BuildArtifactBucketARN}/*
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:GetObjectVersion
            Resource: !Sub ${ProtonTemplatesBucketARN}/*
          - Effect: Allow
            Action: iam:PassRole
            Resource: !Ref ProtonPipelineServiceRoleArn
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
            Resource: !Sub arn:aws:s3:::aws-proton-preview-public-files/*
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: !GetAtt CodeBuildLogGroup.Arn
          - Effect: Allow
            Action:
              - proton:*
            Resource: '*' # These are not clearly defined right now

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !If [ IsEnvironment,
          !Join [ "-", [ !Ref TemplateCode, !Ref EnvCode, env, proton, template, codepipeline, role ] ],
          !Join [ "-", [ !Ref TemplateCode, !Ref AppCode, app, proton, template, codepipeline, role ] ],
        ]
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref CodePipelinePolicy
      Tags:
        - Key: TemplateCode
          Value: !Ref TemplateCode

  CodePipelinePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !If [ IsEnvironment,
          !Join [ "-", [ !Ref TemplateCode, !Ref EnvCode, env, proton, template ] ],
          !Join [ "-", [ !Ref TemplateCode, !Ref AppCode, app, proton, template ] ],
        ]
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - codebuild:StartBuild
              - codebuild:BatchGetBuilds
            Resource: !Sub arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${TemplateCode}-*-proton-template
          - Effect: Allow
            Action: iam:PassRole
            Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/${TemplateCode}-codebuild-proton-template
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:GetBucketVersioning
            Resource: !Sub ${BuildArtifactBucketARN}/*

  CodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !If [ IsEnvironment,
          !Join [ "/", [ !Ref TemplateCode, !Ref EnvCode, env, proton-templates, CodeBuildRole ] ],
          !Join [ "/", [ !Ref TemplateCode, !Ref AppCode, app, proton-templates, CodeBuildRole ] ],
        ]
      RetentionInDays: 180

  TemplateVersionDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: !If [ IsEnvironment,
          !Join [ "-", [ !Ref TemplateCode, !Ref EnvCode, env, proton, template, version ] ],
          !Join [ "-", [ !Ref TemplateCode, !Ref AppCode, app, proton, template, version ] ],
        ]
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        AttributeDefinitions:
          - AttributeName: id # template code
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        SSESpecification:
            SSEType: KMS
            SSEEnabled: true
        Tags:
          - Key: TemplateCode
            Value: !Ref TemplateCode

Outputs:
  Name:
    Value: !Ref AWS::StackName
    Export:
      Name: !Sub ${AWS::StackName}-Name 